apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    name: rabbitmq-amqp
  - port: 4369
    name: rabbitmq-epmd
  - port: 5671
    name: rabbitmq-amqps
  - port: 15672
    name: rabbitmq-mgmt
  - port: 25672
    name: rabbitmq-node
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-management
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 15672
    targetPort: 15672
