apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    name: port-5672
  - port: 4369
    name: port-4369
  - port: 5671
    name: port-5671
  - port: 15672
    name: port-15672
  - port: 25672
    name: port-25672
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-management
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 15672
    targetPort: 15672
